export const QUESTION_REQUESTING = 'QUESTION_REQUESTING';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_ERROR = 'QUESTION_ERROR';

export const UPDATE_RESPONSE_REQUESTING = 'UPDATE_RESPONSE_REQUESTING';
export const UPDATE_RESPONSE_SUCCESS = 'UPDATE_RESPONSE_SUCCESS';
export const UPDATE_RESPONSE_ERROR = 'UPDATE_RESPONSE_ERROR';

export const RESULT_REQUESTING = 'RESULT_REQUESTING';
export const RESULT_SUCCESS = 'RESULT_SUCCESS';
export const RESULT_ERROR = 'RESULT_ERROR';
